version: '3'
services:
  springboot-app:
    image: openjdk:17
    build: .
    ports:
      - "2001:2001"  # Expose Spring Boot application to port 2001
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://grandspace-mysql-db:3306/grandspace  # No change needed
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - grandspace-mysql-db

  grandspace-mysql-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grandspace
    ports:
      - "3301:3306"  # Map host port 3301 to MySQL container port 3306