  springboot-app:
    image: grandspacelive:latest  # ✅ Use the correct built Docker image
    build: .
    ports:
      - "2001:2001"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://grandspace-mysql-db:3306/grandspace
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - grandspace-mysql-db


  grandspace-mysql-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grandspace
    ports:
      - "3301:3306"  # Map host port 3301 to MySQL container port 3306